// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: admission.sql

package pgdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAdmission = `-- name: CreateAdmission :one
INSERT INTO admissions (
  course_code,
  full_name,
  father_name,
  mother_name,
  dob,
  gender,
  religion,
  category,
  sub_category,
  caste_certificate_number,
  is_ews,
  domicile_certificate_number,
  domicile_state,
  mobile,
  email,
  status
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16
)
RETURNING id, course_code, full_name, father_name, mother_name, dob, gender, religion, category, sub_category, caste_certificate_number, is_ews, domicile_certificate_number, domicile_state, mobile, email, status, created_at, updated_at
`

type CreateAdmissionParams struct {
	CourseCode                string      `json:"course_code"`
	FullName                  string      `json:"full_name"`
	FatherName                string      `json:"father_name"`
	MotherName                string      `json:"mother_name"`
	Dob                       pgtype.Date `json:"dob"`
	Gender                    string      `json:"gender"`
	Religion                  string      `json:"religion"`
	Category                  string      `json:"category"`
	SubCategory               pgtype.Text `json:"sub_category"`
	CasteCertificateNumber    pgtype.Text `json:"caste_certificate_number"`
	IsEws                     bool        `json:"is_ews"`
	DomicileCertificateNumber pgtype.Text `json:"domicile_certificate_number"`
	DomicileState             string      `json:"domicile_state"`
	Mobile                    string      `json:"mobile"`
	Email                     string      `json:"email"`
	Status                    string      `json:"status"`
}

func (q *Queries) CreateAdmission(ctx context.Context, arg CreateAdmissionParams) (Admission, error) {
	row := q.db.QueryRow(ctx, createAdmission,
		arg.CourseCode,
		arg.FullName,
		arg.FatherName,
		arg.MotherName,
		arg.Dob,
		arg.Gender,
		arg.Religion,
		arg.Category,
		arg.SubCategory,
		arg.CasteCertificateNumber,
		arg.IsEws,
		arg.DomicileCertificateNumber,
		arg.DomicileState,
		arg.Mobile,
		arg.Email,
		arg.Status,
	)
	var i Admission
	err := row.Scan(
		&i.ID,
		&i.CourseCode,
		&i.FullName,
		&i.FatherName,
		&i.MotherName,
		&i.Dob,
		&i.Gender,
		&i.Religion,
		&i.Category,
		&i.SubCategory,
		&i.CasteCertificateNumber,
		&i.IsEws,
		&i.DomicileCertificateNumber,
		&i.DomicileState,
		&i.Mobile,
		&i.Email,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (
  admission_id,
  order_id,
  amount,
  currency,
  payment_session_id,
  status
) VALUES (
  $1, $2, $3, $4, $5, $6
)
RETURNING id, admission_id, order_id, amount, currency, payment_session_id, cf_payment_id, status, payment_method, transaction_time, created_at, updated_at
`

type CreatePaymentParams struct {
	AdmissionID      int32          `json:"admission_id"`
	OrderID          string         `json:"order_id"`
	Amount           pgtype.Numeric `json:"amount"`
	Currency         string         `json:"currency"`
	PaymentSessionID string         `json:"payment_session_id"`
	Status           string         `json:"status"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, createPayment,
		arg.AdmissionID,
		arg.OrderID,
		arg.Amount,
		arg.Currency,
		arg.PaymentSessionID,
		arg.Status,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.AdmissionID,
		&i.OrderID,
		&i.Amount,
		&i.Currency,
		&i.PaymentSessionID,
		&i.CfPaymentID,
		&i.Status,
		&i.PaymentMethod,
		&i.TransactionTime,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAdmission = `-- name: GetAdmission :one
SELECT id, course_code, full_name, father_name, mother_name, dob, gender, religion, category, sub_category, caste_certificate_number, is_ews, domicile_certificate_number, domicile_state, mobile, email, status, created_at, updated_at FROM admissions
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetAdmission(ctx context.Context, id int32) (Admission, error) {
	row := q.db.QueryRow(ctx, getAdmission, id)
	var i Admission
	err := row.Scan(
		&i.ID,
		&i.CourseCode,
		&i.FullName,
		&i.FatherName,
		&i.MotherName,
		&i.Dob,
		&i.Gender,
		&i.Religion,
		&i.Category,
		&i.SubCategory,
		&i.CasteCertificateNumber,
		&i.IsEws,
		&i.DomicileCertificateNumber,
		&i.DomicileState,
		&i.Mobile,
		&i.Email,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCourse = `-- name: GetCourse :one
SELECT code, name, fee_amount FROM courses
WHERE code = $1 LIMIT 1
`

func (q *Queries) GetCourse(ctx context.Context, code string) (Course, error) {
	row := q.db.QueryRow(ctx, getCourse, code)
	var i Course
	err := row.Scan(&i.Code, &i.Name, &i.FeeAmount)
	return i, err
}

const getPaymentByOrderID = `-- name: GetPaymentByOrderID :one
SELECT id, admission_id, order_id, amount, currency, payment_session_id, cf_payment_id, status, payment_method, transaction_time, created_at, updated_at FROM payments
WHERE order_id = $1 LIMIT 1
`

func (q *Queries) GetPaymentByOrderID(ctx context.Context, orderID string) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByOrderID, orderID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.AdmissionID,
		&i.OrderID,
		&i.Amount,
		&i.Currency,
		&i.PaymentSessionID,
		&i.CfPaymentID,
		&i.Status,
		&i.PaymentMethod,
		&i.TransactionTime,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCourses = `-- name: ListCourses :many
SELECT code, name, fee_amount FROM courses
ORDER BY name
`

func (q *Queries) ListCourses(ctx context.Context) ([]Course, error) {
	rows, err := q.db.Query(ctx, listCourses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Course{}
	for rows.Next() {
		var i Course
		if err := rows.Scan(&i.Code, &i.Name, &i.FeeAmount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAdmissionStatus = `-- name: UpdateAdmissionStatus :one
UPDATE admissions
SET status = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, course_code, full_name, father_name, mother_name, dob, gender, religion, category, sub_category, caste_certificate_number, is_ews, domicile_certificate_number, domicile_state, mobile, email, status, created_at, updated_at
`

type UpdateAdmissionStatusParams struct {
	ID     int32  `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateAdmissionStatus(ctx context.Context, arg UpdateAdmissionStatusParams) (Admission, error) {
	row := q.db.QueryRow(ctx, updateAdmissionStatus, arg.ID, arg.Status)
	var i Admission
	err := row.Scan(
		&i.ID,
		&i.CourseCode,
		&i.FullName,
		&i.FatherName,
		&i.MotherName,
		&i.Dob,
		&i.Gender,
		&i.Religion,
		&i.Category,
		&i.SubCategory,
		&i.CasteCertificateNumber,
		&i.IsEws,
		&i.DomicileCertificateNumber,
		&i.DomicileState,
		&i.Mobile,
		&i.Email,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePaymentStatus = `-- name: UpdatePaymentStatus :one
UPDATE payments
SET status = $2,
    cf_payment_id = $3,
    payment_method = $4,
    transaction_time = $5,
    updated_at = NOW()
WHERE id = $1
RETURNING id, admission_id, order_id, amount, currency, payment_session_id, cf_payment_id, status, payment_method, transaction_time, created_at, updated_at
`

type UpdatePaymentStatusParams struct {
	ID              int32              `json:"id"`
	Status          string             `json:"status"`
	CfPaymentID     pgtype.Text        `json:"cf_payment_id"`
	PaymentMethod   pgtype.Text        `json:"payment_method"`
	TransactionTime pgtype.Timestamptz `json:"transaction_time"`
}

func (q *Queries) UpdatePaymentStatus(ctx context.Context, arg UpdatePaymentStatusParams) (Payment, error) {
	row := q.db.QueryRow(ctx, updatePaymentStatus,
		arg.ID,
		arg.Status,
		arg.CfPaymentID,
		arg.PaymentMethod,
		arg.TransactionTime,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.AdmissionID,
		&i.OrderID,
		&i.Amount,
		&i.Currency,
		&i.PaymentSessionID,
		&i.CfPaymentID,
		&i.Status,
		&i.PaymentMethod,
		&i.TransactionTime,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
