// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package pgdb

import (
	"context"
)

type Querier interface {
	UserLogin(ctx context.Context, arg UserLoginParams) (User, error)
}

var _ Querier = (*Queries)(nil)
