// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package pgdb

import (
	"context"
)

const userLogin = `-- name: UserLogin :one
SELECT id, email, password FROM users
WHERE id = $1 OR email = $2
LIMIT 1
`

type UserLoginParams struct {
	ID    int32  `json:"id"`
	Email string `json:"email"`
}

func (q *Queries) UserLogin(ctx context.Context, arg UserLoginParams) (User, error) {
	row := q.db.QueryRow(ctx, userLogin, arg.ID, arg.Email)
	var i User
	err := row.Scan(&i.ID, &i.Email, &i.Password)
	return i, err
}
